apiVersion: batch/v1
kind: Job
metadata:
  name: find-hash-coarse
spec:
  completions: 4
  parallelism: 2
  template:
    metadata:
      name: find-hash-coarse
    spec:
      containers:
      - name: find-hash
        image: gcr.io/winter-legend-167417/find-hash-coarse
        env:
        - name: BROKER_URL
          value: amqp://guest:guest@rabbitmq-service:5672
        - name: QUEUE
          value: job
      restartPolicy: OnFailure
