apiVersion: batch/v1
kind: Job
metadata:
  name: find-hash-wq
spec:
  parallelism: 2
  template:
    metadata:
      name: find-hash-wq
    spec:
      containers:
      - name: find-hash-wq
        image: docker.io/vinhags/find-the-hash-wq:encrypted
        command: ["python", "finddahash.py"]
        env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: appkey
              key: password.txt
        imagePullPolicy: Always
      restartPolicy: OnFailure
      
