apiVersion: batch/v1
kind: Job
metadata:
  name: finddahash-random
spec:
  completions: 2
  parallelism: 3
  template:
    metadata:
      name: finddahash-random
    spec:
      containers:
      - name: finddahash-random
        image: gcr.io/winter-legend-167417/finddahash-random
        command: ["python", "finddahash.py", "ababab", "1000000"]
      restartPolicy: OnFailure
