apiVersion: batch/v1
kind: Job
metadata:
  name: finddahash-random
spec:
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: finddahash-random
    spec:
      containers:
      - name: finddahash-random
        image: gcr.io/winter-legend-167417/finddahash-random
        command: ["python", "finddahash.py", "78880"]
      restartPolicy: Never
